<h4 class='prehead'>SM286D &middot; Introduction to Applied Mathematics with Python &middot; Spring 2020 &middot; Uhan</h4>

<h1 class='lesson_title'>Quiz 5 &mdash; 26 March 2020</h1>

## Instructions

You have 25 minutes to complete this quiz. __This quiz is due on Thursday 26 March at 23:59.__

You may use your own course materials (e.g. notes, textbook), as well as any materials directly linked from the [class website](https://www.usna.edu/Users/math/uhan/sm286d/). __No collaboration allowed.__ All work in this quiz must be your own.

There are a total of 4 problems, worth 15 points.

Save your work frequently! When you are finished, submit this file using the SM286D Assignment Submission Form linked on the [class website](https://www.usna.edu/Users/math/uhan/sm286d/).

---

## Your signature required here

By typing your name in the box below, you pledge on your honor that you have used only the allotted time, that you have not used any unauthorized materials, and that you have not given or received any unauthorized assistance.

<span style="color:red"><strong>WRITE YOUR NAME IN THIS BOX. DOUBLE-CLICK TO EDIT.</strong></span>

---

## Problem 1 (4 points)

Consider the graph $G$ below in Figure 1.

<img src="img/graph_quiz_5a.png" alt="Drawing" style="width: 400px;"/>

<center> Figure 1: The graph of $G$. </center>

The code in the cell below starts to define the adjacency matrix $A$ for the graph $G$.  

Replace __only__ the `...` in the code below with appropriate values to complete the definition of $A$.

In [1]:
import numpy as np

A = np.zeros([8, 8])
A[0, [1, 2]] = 1
A[1, [0, 2, 3, 5]] = 1
A[2, [0, 1, 4, 6]] = 1
A[3, [1, 4, 5, 7]] = 1
A[4, [2 ,3, 6, 7]] = 1
A[5, [1, 3]] = 1
A[6, [2, 4]] = 1
A[7, [3, 4]] = 1

## Problem 2 (1 point)

Use NetworkX and the adjacency matrix $A$ from Problem 1 to define the graph $G$ in Figure 1, by replacing the `...` below with appropriate code.

In [2]:
import networkx as nx
G = nx.Graph(A)

## Problem 3 (4 points)

Use the method `G.nodes()` to define a list called `nodes_list` consisting of the nodes of `G`. Then loop over `nodes_list` and use the method `G.neighbors(n)` to print the list of neighbors for each node in the graph $G$. Your output should look like this:

```
The neighbors of node 0 are the elements of the list [1, 2].
The neighbors of node 1 are the elements of the list [0, 2, 3, 5].
The neighbors of node 2 are the elements of the list [0, 1, 4, 6].
The neighbors of node 3 are the elements of the list DETERMINED BY YOUR CODE.
The neighbors of node 4 are the elements of the list DETERMINED BY YOUR CODE.
The neighbors of node 5 are the elements of the list DETERMINED BY YOUR CODE.
The neighbors of node 6 are the elements of the list DETERMINED BY YOUR CODE.
The neighbors of node 7 are the elements of the list DETERMINED BY YOUR CODE.
```

If you were unable to correctly answer Problems 1 or 2, or if you can't get the methods of `G` to work properly, you can earn partial credit by producing the output above manually: in other words, create and print the sentences above manually by looking at the graph $G$ given in Figure 1.

In [3]:
# First use G.nodes() to define the list nodes_list
nodes_list = list(G.nodes())

# Write your for loop below
for n in nodes_list:
    node_neighbors = list(G.neighbors(n))
    print(f'The neighbors of node {n} are the elements of the list {node_neighbors}.')

The neighbors of node 0 are the elements of the list [1, 2].
The neighbors of node 1 are the elements of the list [0, 2, 3, 5].
The neighbors of node 2 are the elements of the list [0, 1, 4, 6].
The neighbors of node 3 are the elements of the list [1, 4, 5, 7].
The neighbors of node 4 are the elements of the list [2, 3, 6, 7].
The neighbors of node 5 are the elements of the list [1, 3].
The neighbors of node 6 are the elements of the list [2, 4].
The neighbors of node 7 are the elements of the list [3, 4].


## Problem 4 (6 points total)

For this problem, you will use the matrices $B$ and $C$ defined below.

\begin{equation*}
B = \begin{bmatrix}  2 & 0 & 1 & 3\\
0 & 2 & 3 & 4\\
0 & 4 & 5 & 1\\
1 & 2 & 7 & 6\end{bmatrix}
\end{equation*}

\begin{equation*}
C = \begin{bmatrix}  2 & 4 & 6 \\
1 & 3 & 5 \\
0 & 1 & 2 \\
3 & 5 & 2\end{bmatrix}
\end{equation*}

### a. (2 points)
In the code cell below, the matrix $B$ is correctly defined.  Replace `...` and write similar code to correctly define $C$.

In [4]:
B = np.array([[2, 0, 1, 3], [0, 2, 3, 4], [0, 4, 5, 1], [1, 2, 7, 6]])
C = np.array([[2, 4, 6], [1, 3, 5], [0, 1, 2], [3, 5, 2]])

### b. (2 points) 
Find and print $BC$. (Note that this is __matrix__ multiplication.)

In [5]:
print(B @ C)

[[13 24 20]
 [14 29 24]
 [ 7 22 32]
 [22 47 42]]


### c. (2 points)
Use the appropriate method from `np.linalg` to find the determinant of $B$.  Print the value of the determinant in a nicely formatted sentence similar to the one below.

```
The determinant of B is 45.00.
```

For full credit, the determinant value **must** be displayed with 2 decimal places of precision.

In [6]:
import numpy as np

# Write your answer to Problem 4c below
print(f"The determinant of B is {np.linalg.det(B):.2f}.")

The determinant of B is 96.00.


---

## When you're finished

* Select **Cell &#8594; Run All**  to run all the cells from top to bottom. Make sure your notebook runs as you expect before submitting it.

* Submit this file using the SM286D Assignment Submission Form linked on the [class website](https://www.usna.edu/Users/math/uhan/sm286d/).